### ISSUE TITLE
Presentation doesn't work properly

### ISSUE THREAD

**Issue by edrcq** [YoutubeLike/CodingTube#142]
- Lien video ?
- Categories dans le menu ?

**Comment by edrcq** [comment]
C'est une team de grand gamer, c'est surement normal

**Comment by Nicolas-Dobosz** [comment]
Fait

**Comment by NonoIceOff** [comment]
Les catégories dans le burger menu ont été remis

**Comment by NonoIceOff** [comment]
Toutes les vidéos mènent désormais sur la page Vidéos
